defaults: &defaults
  working_directory: /go/src/github.com/meepshop/network_usage_analysis
  docker:
    - image: circleci/golang:1.9
      environment:
          GOPATH: /go

version: 2
jobs:
  cache_workspace:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ./
          paths:
            - ./
  docker_deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main main.go
      - setup_remote_docker
      - deploy:
          name: Docker Provision
          command: |
            if [[ -z "${HARBORMASTER_BUILD_TARGET_PHID}" && -z "${CIRCLE_PULL_REQUEST}" ]]; then
              chmod +x ./.circleci/deploy-docker.sh
              ./.circleci/deploy-docker.sh
            fi
  kubernetes_deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - deploy:
          name: Kubernetes Provision
          command: |
            if [[ -z "${HARBORMASTER_BUILD_TARGET_PHID}" && "${CIRCLE_BRANCH}" == "master" ]]; then
                chmod +x ./.circleci/deploy-kubernetes.sh
                ./.circleci/deploy-kubernetes.sh
            fi

workflows:
  version: 2
  build-workflow:
    jobs:
      - cache_workspace:
          filters:
            tags:
              only: /.*/
      - docker_deploy:
          requires:
            - cache_workspace
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          context: org-global
      - kubernetes_deploy:
          requires:
            - docker_deploy
          filters:
            branches:
              only: master
          context: org-global